import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { ok, notFound, serverError } from '#core/utils/apiResponse.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
let __CNAE_CACHE = { data: null, mtime: 0, path: path.join(__dirname, '../../../../public/data/cnaes_lista.json') };
function loadCnaesFile() { try { const stat = fs.statSync(__CNAE_CACHE.path); if (!__CNAE_CACHE.data || stat.mtimeMs !== __CNAE_CACHE.mtime) { const raw = fs.readFileSync(__CNAE_CACHE.path, 'utf8'); __CNAE_CACHE.data = JSON.parse(raw); __CNAE_CACHE.mtime = stat.mtimeMs; console.log('[CNAE] cache recarregado:', __CNAE_CACHE.data.length, 'itens'); } } catch (e) { console.error('[CNAE] falha ao carregar arquivo', e.message); __CNAE_CACHE.data = []; } return __CNAE_CACHE.data || []; }
export function listarCnaes(req,res){ try { const all = loadCnaesFile(); const { page = '1', limit = '100', search = '', natureza = '' } = req.query; let p = parseInt(page, 10); if (isNaN(p) || p < 1) p = 1; let l = parseInt(limit, 10); if (isNaN(l) || l < 1) l = 100; if (l > 300) l = 300; const s = String(search || '').trim().toLowerCase(); const nat = String(natureza || '').trim(); const fil = all.filter(c => { if (nat) { if (!Array.isArray(c.naturezas_juridicas) || !c.naturezas_juridicas.includes(nat)) return false; } if (!s) return true; const codigo = (c.codigo || c.cod || '').toLowerCase(); const desc = (c.descricao || c.desc || '').toLowerCase(); if (/^[0-9 .\-\/]+$/.test(s)) { const norm = codigo.replace(/\D/g,''); const target = s.replace(/\D/g,''); return norm.includes(target); } return (codigo + ' ' + desc).includes(s); }); const total = fil.length; const start = (p - 1) * l; const items = fil.slice(start, start + l); return ok(res, items, { page:p, limit:l, total, pages: Math.ceil(total / l) }); } catch(err){ return serverError(res, err); } }
export function obterCnae(req,res){ try { const all = loadCnaesFile(); const codeReq = String(req.params.codigo).toLowerCase(); const found = all.find(c => String(c.codigo || c.cod || '').toLowerCase() === codeReq); if (!found) return notFound(res, 'CNAE não encontrado'); return ok(res, found); } catch(err){ return serverError(res, err); } }
