import { deleteUserById, findUserById } from '#modules/gestor/app/services/apiDbBridgeService.js';
import { ok, badRequest, notFound, serverError } from '#core/utils/apiResponse.js';
import { toggleUsuarioExecutionService } from '#modules/gestor/app/services/usuarios/toggleUsuarioExecution.service.js';
import { deleteUsuarioExecutionService } from '#modules/gestor/app/services/usuarios/deleteUsuarioExecution.service.js';
import { updateUsuarioAdminExecutionService } from '#modules/gestor/app/services/usuarios/updateUsuarioAdminExecution.service.js';
function isAdminOrMaster(req){ if(!req.user) return false; const role = (req.user.role||'').toLowerCase(); return req.user.isMaster || role === 'master' || role === 'admin'; }
export async function toggleUsuario(req,res){ try { const { id } = req.params; if(!isAdminOrMaster(req)) return badRequest(res,'Apenas admin ou master podem alterar usuários'); const user = await findUserById(id); if(!user) return notFound(res,'Usuário não encontrado'); if(user.role === 'master' && !req.user.isMaster && req.user.role !== 'master') return badRequest(res,'Apenas master pode alterar usuário master'); const toggleResult = await toggleUsuarioExecutionService({ user }); return ok(res,{ id:(toggleResult?._id || user._id), ativo:(toggleResult?.ativo ?? user.ativo) }); } catch(e){ return serverError(res,e); } }
export async function updateUsuario(req,res){ try { const { id } = req.params; if(!isAdminOrMaster(req)) return badRequest(res,'Apenas admin ou master podem alterar usuários'); const { email, role } = req.body || {}; const user = await findUserById(id); if(!user) return notFound(res,'Usuário não encontrado'); if(user.role === 'master' && !req.user.isMaster && req.user.role !== 'master') return badRequest(res,'Apenas master pode alterar usuário master'); if(role){ if(user.role === 'master' && role !== 'master' && !req.user.isMaster) return badRequest(res,'Apenas master pode alterar role de master'); if(role === 'master' && !req.user.isMaster) return badRequest(res,'Promoção a master não permitida'); } const updateResult = await updateUsuarioAdminExecutionService({ user, email: email ? String(email).toLowerCase() : '', role: role || '' }); return ok(res,{ id:(updateResult?._id || user._id), email:(updateResult?.email ?? user.email), role:(updateResult?.role ?? user.role), ativo:(updateResult?.ativo ?? user.ativo) }); } catch(e){ return serverError(res,e); } }
export async function deleteUsuario(req,res){ try { const { id } = req.params; if(!isAdminOrMaster(req)) return badRequest(res,'Apenas admin ou master podem excluir usuários'); const user = await findUserById(id); if(!user) return notFound(res,'Usuário não encontrado'); if(user.role === 'master' && !req.user.isMaster && req.user.role !== 'master') return badRequest(res,'Apenas master pode excluir usuário master'); await deleteUsuarioExecutionService({ userId: id, vinculoFuncionarioId: user?.funcionario_id || null }); return ok(res,{ id, deleted:true }); } catch(e){ return serverError(res,e); } }
